### ISSUE TITLE
Password Reset

### ISSUE THREAD

**Issue by jonsparks** [HydridSystems/Hydrid-CAD-MDT#21]
There is currently no user-accessible password reset function. Since most people end up with tons of online accounts, it is fairly common to occasionally forget a password (especially when you use a different one for every site/account). 

**Describe the solution you'd like**
Ideally, there would be some sort of password reset function with a link below the login box. This could simply change the user's password to a randomly generated token and email it to the address associated with the account. Alternatively, it could send an email link to verify the user's identity and use that token to initiate the password reset.

**Describe alternatives you've considered**
The only alternative for lost passwords would be to require users to contact their administrator and request a reset. Manual intervention is not ideal since it relies on somebody being online and available to handle the request.

**Comment by lilfuchs** [comment]
And an alternative to this could actually be steam login. which is rather easy to add and not sure why the cad doesn't have it as it would most likely be a lot safer than manual login.

**Comment by justinfarmer14** [comment]
Sorry for the late reply Jon
We are looking into this ASAP!
