### ISSUE TITLE
In Game Tablet

### ISSUE THREAD

**Issue by FroztIkon** [HydridSystems/Hydrid-CAD-MDT#22]
**Is your feature request related to a problem? Please describe.**
Using other tablets released by the community, it doesn't allow for the drop down selections. IE choosing a identifier.

**Describe the solution you'd like**
An ingame tablet that doesn't use the drop down selector so that the selector is either pre-selected (in case of single person selector) or a checkbox type display with select box at the bottom (like a list then a 'ok' button).

**Describe alternatives you've considered**
Don't think there are alternatives to this.

**Additional context**
None at this moment.

**Comment by dhawton** [comment]
This happens on other CAD systems and is most likely related to the browser engine implemented in game rather than an issue with CAD.

**Comment by justinfarmer14** [comment]
Hi this is Farmer from HydridSystems 

I’m a project supervisor so in response to your inquiry that’s a bit out of our scope of support but if you wish to contact the person who originally created it and have him contact us we be happy to make sure all future builds work thanks 

Farmer
Poi!?!

**Comment by ScottUK** [comment]
I will add this in the next update for V2 🙃
