### ISSUE TITLE
Unable to create calls from dispatch panel

### ISSUE THREAD

**Issue by mmcguire1** [HydridSystems/Hydrid-CAD-MDT#28]
when on the dispatch page you can see 911 calls come in from civs but Dispatch cannot use the create call button to create a new call 
I expect that when you press the create call button with all the information in the form it will display it in the active call section and be able to be seen by the dispatcher and be able to assign that call to people

**Comment by ArranLH** [comment]
V1 or V2

**Comment by ArranLH** [comment]
Hmmm... what PHP version and if you know the MYSQL version that would be nice too

**Comment by mmcguire1** [comment]
MYSQL: 5.7.23
PHP: 7.2.1

these are the only ones I know we are hosting it off a WAMP server with the address 
http://usainwa.servebeer.com/cad
