### ISSUE TITLE
Ability to view supervisor panel without being supervisor

### ISSUE THREAD

**Issue by ArranLH** [HydridSystems/Hydrid-CAD-MDT#32]
**Describe the bug**
You can see supervisor options without being supervisor.

**To Reproduce**
1. Go to leo.php?v=supervisor
2. You can also see it on the LEO console

**Screenshots**
https://i.imgur.com/TEfwSJW.png
https://i.imgur.com/VfVn1q5.png

**Desktop (please complete the following information):**
Windows 10
Chrome
Unknown

**Comment by Tyler-HS** [comment]
Super Admins can access supervisor options without needing to be supervisor.
